FROM node:latest

WORKDIR /code

COPY package.json /code
COPY package-lock.json /code

RUN npm install --legacy-peer-deps

RUN mkdir src
COPY . /code

RUN npm run build

# CMD ["npm", "run", "serve", "--", "--port", "3000"]