export const ACTIVATION_BEGIN = 'ACTIVATION_BEGIN';
export const ACTIVATION_CLEAR = 'ACTIVATION_CLEAR';
export const ACTIVATION_ERROR = 'ACTIVATION_ERROR';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_CLEAR = 'LOGIN_CLEAR';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const PASSWORD_EMAIL_BEGIN = 'PASSWORD_EMAIL_BEGIN';
export const PASSWORD_EMAIL_CLEAR = 'PASSWORD_EMAIL_CLEAR';
export const PASSWORD_EMAIL_ERROR = 'PASSWORD_EMAIL_ERROR';
export const PASSWORD_EMAIL_SUCCESS = 'PASSWORD_EMAIL_SUCCESS';
export const PASSWORD_RESET_BEGIN = 'PASSWORD_RESET_BEGIN';
export const PASSWORD_RESET_CLEAR = 'PASSWORD_RESET_CLEAR';
export const PASSWORD_RESET_ERROR = 'PASSWORD_RESET_ERROR';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const REGISTRATION_BEGIN = 'REGISTRATION_BEGIN';
export const REGISTRATION_CLEAR = 'REGISTRATION_CLEAR';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const SET_TOKEN = 'SET_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';


export const WORDLE_STATUS_BEGIN = 'WORDLE_STATUS_BEGIN';
export const WORDLE_STATUS_ERROR = 'WORDLE_STATUS_ERROR';
export const WORDLE_STATUS_SUCCESS = 'WORDLE_STATUS_SUCCESS';


export const WORDLE_GUESS_BEGIN = 'WORDLE_GUESS_BEGIN';
export const WORDLE_GUESS_ERROR = 'WORDLE_GUESS_ERROR';
export const WORDLE_GUESS_SUCCESS = 'WORDLE_GUESS_SUCCESS';
export const WORDLE_GUESS_RESPONDED = 'WORDLE_GUESS_RESPONDED';

export const WORDLE_TODAY_BEGIN = 'WORDLE_TODAY_BEGIN'
export const WORDLE_TODAY_ERROR = 'WORDLE_TODAY_ERROR'
export const WORDLE_TODAY_SUCCESS = 'WORDLE_TODAY_SUCCESS'
export const WORDLE_LEADERS_BEGIN = 'WORDLE_LEADERS_BEGIN'
export const WORDLE_LEADERS_ERROR = 'WORDLE_LEADERS_ERROR'
export const WORDLE_LEADERS_SUCCESS = 'WORDLE_LEADERS_SUCCESS'
