# Generated by Django 4.0.3 on 2022-06-16 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activewordle',
            options={'verbose_name': 'Active Wordle', 'verbose_name_plural': 'Active Wordles'},
        ),
    ]
