/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarGraph: typeof import('./components/graphs/BarGraph.vue')['default']
    BigNumberCard: typeof import('./components/BigNumberCard.vue')['default']
    DashboardListCard: typeof import('./components/DashboardListCard.vue')['default']
    ExtraWordleRankingsCard: typeof import('./components/wordle/ExtraWordleRankingsCard.vue')['default']
    MyWordleCard: typeof import('./components/MyWordleCard.vue')['default']
    NavBarComponent: typeof import('./components/NavBarComponent.vue')['default']
    NextWordleCard: typeof import('./components/wordle/NextWordleCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchTable: typeof import('./components/SearchTable.vue')['default']
    StaticWordleComponent: typeof import('./components/wordle/StaticWordleComponent.vue')['default']
    TestWordleComponent: typeof import('./components/wordle/TestWordleComponent.vue')['default']
    TimeClockComponent: typeof import('./components/wordle/TimeClockComponent.vue')['default']
    UserProfilePicture: typeof import('./components/UserProfilePicture.vue')['default']
    UserSelfComponent: typeof import('./components/UserSelfComponent.vue')['default']
    UserSessionCard: typeof import('./components/UserSessionCard.vue')['default']
    UsersSearchComponent: typeof import('./components/UsersSearchComponent.vue')['default']
    UserViewComponent: typeof import('./components/UserViewComponent.vue')['default']
    UserWordleGameComponent: typeof import('./components/wordle/UserWordleGameComponent.vue')['default']
    WordDefinitionCard: typeof import('./components/wordle/WordDefinitionCard.vue')['default']
    WordleCard: typeof import('./components/wordle/WordleCard.vue')['default']
    WordleDisplay: typeof import('./components/wordle/WordleDisplay.vue')['default']
    WordsSearchComponent: typeof import('./components/WordsSearchComponent.vue')['default']
    WordViewComponent: typeof import('./components/WordViewComponent.vue')['default']
  }
}
