# Generated by Django 3.0.3 on 2022-04-20 04:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRating',
            fields=[
                ('player', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Player')),
                ('rating', models.IntegerField(default=None)),
            ],
            options={
                'verbose_name': 'player_rating',
                'verbose_name_plural': 'player_ratings',
                'db_table': 'player_rating',
            },
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'match', 'verbose_name_plural': 'matchs'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='coefficient',
        ),
        migrations.RemoveField(
            model_name='event',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='match',
            name='delta',
        ),
        migrations.RemoveField(
            model_name='match',
            name='event',
        ),
        migrations.RemoveField(
            model_name='match',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='match',
            name='event_phase',
        ),
        migrations.RemoveField(
            model_name='match',
            name='is_technical',
        ),
        migrations.RemoveField(
            model_name='match',
            name='loser_rating',
        ),
        migrations.RemoveField(
            model_name='match',
            name='loser_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner_rating',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner_score',
        ),
        migrations.RemoveField(
            model_name='player',
            name='city',
        ),
        migrations.RemoveField(
            model_name='player',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='player',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hand',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='player',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='match',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='match',
            name='losing_score',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='match',
            name='winning_score',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='core.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='won_matches', to='core.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='RatingHistory',
        ),
    ]
