# Generated by Django 3.0.3 on 2022-05-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activewordle_dailywordle_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activewordle',
            name='word',
            field=models.CharField(default='bingo', max_length=5),
        ),
    ]
