# Generated by Django 3.0.3 on 2022-05-24 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220524_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activewordle',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activewordle',
            name='word',
            field=models.CharField(max_length=5),
        ),
    ]
