# Generated by Django 3.0.3 on 2022-05-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220524_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activewordle',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
