# Generated by Django 3.0.3 on 2022-05-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220524_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywordle',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
