# Generated by Django 3.0.3 on 2022-05-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220524_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywordle',
            name='fail',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
