# Generated by Django 3.0.3 on 2022-05-25 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dailywordle_fail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 4, 55, 40, 596817)),
        ),
    ]
