# Generated by Django 3.0.3 on 2022-05-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220525_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
